#if !canImport(ObjectiveC)
import XCTest

extension BinaryHeapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryHeapTests = [
        ("testCount", testCount),
        ("testHeapify", testHeapify),
        ("testIndex", testIndex),
        ("testIsEmpty", testIsEmpty),
        ("testPop", testPop),
        ("testPopAndPush", testPopAndPush),
        ("testPush", testPush),
        ("testRemove", testRemove),
        ("testSequence", testSequence),
    ]
}

extension CircularBufferTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CircularBufferTests = [
        ("testAppendAndPopLast", testAppendAndPopLast),
        ("testCount", testCount),
        ("testIndex", testIndex),
        ("testIsEmpty", testIsEmpty),
        ("testPrependAndPopFirst", testPrependAndPopFirst),
        ("testRemoveAt", testRemoveAt),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BinaryHeapTests.__allTests__BinaryHeapTests),
        testCase(CircularBufferTests.__allTests__CircularBufferTests),
    ]
}
#endif
